### ISSUE TITLE
Support Play 2.5

### ISSUE THREAD

**Issue by camuthig** [zalando/scala-jsonapi#55]
The current documented play-json version is causing errors with Play 2.5 applications. 

> java.lang.NoSuchMethodError: play.api.libs.functional.syntax.package$.functionalCanBuildApplicative(Lplay/api/libs/functional/Applicative;)Lplay/api/libs/functional/FunctionalCanBuild;
	at org.zalando.jsonapi.json.playjson.PlayJsonJsonapiFormat$class.rootObjectFormat(PlayJsonJsonapiFormat.scala:18)
	at org.zalando.jsonapi.json.playjson.PlayJsonJsonapiSupport$.rootObjectFormat$lzycompute(PlayJsonJsonapiSupport.scala:19)
	at org.zalando.jsonapi.json.playjson.PlayJsonJsonapiSupport$.rootObjectFormat(PlayJsonJsonapiSupport.scala:19)

**Comment by zmeda** [comment]
Is this issue now "solved" by using proper dependencies and updated README?

**Comment by camuthig** [comment]
Just based on the changes in the documentation, this error still occurs on Play 2.5 apps. I was able to correct this problem locally (haven't yet pushed this change to my fork yet) by updating the scala-jsonapi build.sbt to use an up to date play-json depdendency:

`"com.typesafe.play" %% "play-json"              % "2.5.4"      % "provided",`

However, I am not certain this is a backwards safe change, so it would lead me to think a major release increase would be needed. 

Another solution I thought of, still not necessarily backwards compatible from 0.5.0 , would be to break up the project to be more modular. Instead of depending on `scala-jsonapi`, consumers could depend on `play-scala-jsonapi` or `spray-scala-jsonapi`. Each of these would in turn rely on `scala-jsonapi` for the bulk of the logic and really just provide wrappers around the actual JSON support. This could give two major improvements from my point of view:

1. It allows each support module to be upgraded independently based on changes in the external packages.
1. It allows for projects like `play-scala-jsonapi` to explicitly bring in Spray based packages that Play developers normally wouldn't think to include, fixing some of the documentation confusion as well.

**Comment by nehalium** [comment]
Can you override the dependency by adding this to `project/plugins.sbt` in your project?

```
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.5.4" % "provided"
```

**Comment by zmeda** [comment]
I was also thinking of splitting this into more modular pieces, namely:

- `scala-jsonapi-core` - which would only have domain model definition and upstream transformation (reader and writer definition, etc.)
- `scala-jsonapi-spray` - which would use `core` underneath (ofc) and all necessary spray-json and spray.io (marshallers and unmarshallers) needed
- `scala-jsonapi-play` - same as above just for play
- `scala-jsonapi-akkahttp` - spray-json + akkahttp (un)marshallers

I tried to achieve this by having one repo (one project as it is now) and just using `provided` library dependencies. If you think separating makes more sense I'd love to work on that.

Please give feedback.

**Comment by camuthig** [comment]
Sorry for the **very** slow response. I was kinda dragged away from this.

@nehalium I tried adding the line to my plugins.sbt and just get a dependency issue (`Unresolved dependency`). Adding it directly to my build.sbt though did not throw any build errors, but also still did not solve the underlying problem.

**Comment by ysihaoy** [comment]
Does it support Play framework 2.5 or not? I thought already supported :-)

**Comment by frne** [comment]
@camuthig AFAIK, it is almost impossible to support multiple play-versions when depending on play libs, cause they have bc breaks between minors...

[swagger-play](https://github.com/swagger-api/swagger-play) e.g. did a subtree split and is copying code for each play version. Or you could bump up major version for play 2.5 (depends on versioning scheme).

**Comment by wsargent** [comment]
@frne fyi, Play's versioning scheme is <epoch>.<major>.<minor> -- Play 2.5 is binary incompatible with Play 2.4.

**Comment by frne** [comment]
@wsargent Thx for clarification. That's what I meant...
